# Generated by Django 4.2.7 on 2025-08-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("graph_rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.FloatField()),
                ("rank", models.IntegerField()),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("retrieval", "Retrieved Context"),
                            ("graph", "Graph Context"),
                            ("conversation", "Conversation Context"),
                        ],
                        default="retrieval",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "rag_contexts",
            },
        ),
        migrations.CreateModel(
            name="RAGFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("quality", "Response Quality"),
                            ("relevance", "Content Relevance"),
                            ("accuracy", "Factual Accuracy"),
                            ("completeness", "Response Completeness"),
                        ],
                        default="quality",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "rag_feedback",
            },
        ),
        migrations.CreateModel(
            name="RAGQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("query_text", models.TextField()),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard RAG"),
                            ("graph_rag", "Graph RAG"),
                            ("hybrid", "Hybrid RAG"),
                            ("conversational", "Conversational RAG"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
                ("response_text", models.TextField(blank=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("token_count", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "rag_queries",
            },
        ),
        migrations.CreateModel(
            name="RAGSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("conversation_context", models.JSONField(blank=True, default=list)),
                ("system_prompt", models.TextField(blank=True)),
                ("max_context_length", models.IntegerField(default=4000)),
                ("temperature", models.FloatField(default=0.7)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graph_rag.knowledgegraph",
                    ),
                ),
            ],
            options={
                "db_table": "rag_sessions",
            },
        ),
    ]
