# Generated by Django 4.2.7 on 2025-08-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vector_store", "0001_initial"),
        ("rag_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragquery",
            name="context_chunks",
            field=models.ManyToManyField(
                through="rag_core.RAGContext", to="vector_store.documentchunk"
            ),
        ),
        migrations.AddField(
            model_name="ragquery",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="rag_core.ragsession",
            ),
        ),
        migrations.AddField(
            model_name="ragfeedback",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="rag_core.ragquery",
            ),
        ),
        migrations.AddField(
            model_name="ragcontext",
            name="chunk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vector_store.documentchunk",
            ),
        ),
        migrations.AddField(
            model_name="ragcontext",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rag_core.ragquery"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(
                fields=["session_id"], name="rag_session_session_345a98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragsession",
            index=models.Index(
                fields=["user_id", "created_at"], name="rag_session_user_id_a5988b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["session", "created_at"], name="rag_queries_session_c25131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["query_type"], name="rag_queries_query_t_2dbf7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragquery",
            index=models.Index(
                fields=["processing_time"], name="rag_queries_process_58b81b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragfeedback",
            index=models.Index(fields=["rating"], name="rag_feedbac_rating_a64b64_idx"),
        ),
        migrations.AddIndex(
            model_name="ragfeedback",
            index=models.Index(
                fields=["feedback_type"], name="rag_feedbac_feedbac_346bb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragfeedback",
            index=models.Index(
                fields=["created_at"], name="rag_feedbac_created_15b5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragcontext",
            index=models.Index(
                fields=["relevance_score"], name="rag_context_relevan_59a2ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ragcontext",
            index=models.Index(fields=["rank"], name="rag_context_rank_2264a4_idx"),
        ),
        migrations.AddIndex(
            model_name="ragcontext",
            index=models.Index(
                fields=["context_type"], name="rag_context_context_b25a38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ragcontext",
            unique_together={("query", "chunk")},
        ),
    ]
