# Generated by Django 4.2.7 on 2025-08-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField()),
                ("api_key", models.CharField(blank=True, max_length=255)),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("claude", "Claude MCP"),
                            ("openai", "OpenAI Compatible"),
                            ("custom", "Custom MCP"),
                        ],
                        default="claude",
                        max_length=50,
                    ),
                ),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("max_context_length", models.IntegerField(default=8192)),
            ],
            options={
                "db_table": "mcp_servers",
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("parameters_schema", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="mcp_integration.mcpserver",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_tools",
                "unique_together": {("name", "server")},
            },
        ),
        migrations.CreateModel(
            name="MCPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("completion", "Text Completion"),
                            ("chat", "Chat Completion"),
                            ("embedding", "Embedding"),
                            ("function_call", "Function Call"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt", models.TextField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("response", models.TextField(blank=True)),
                ("response_metadata", models.JSONField(blank=True, default=dict)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="mcp_integration.mcpserver",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_requests",
            },
        ),
        migrations.CreateModel(
            name="MCPToolExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("result", models.TextField(blank=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="mcp_integration.mcprequest",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="mcp_integration.mcptool",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_tool_executions",
                "indexes": [
                    models.Index(
                        fields=["tool", "status"], name="mcp_tool_ex_tool_id_3a4dbf_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="mcp_tool_ex_status_b6a83a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mcprequest",
            index=models.Index(
                fields=["server", "status"], name="mcp_request_server__d3a91a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcprequest",
            index=models.Index(
                fields=["request_type", "created_at"],
                name="mcp_request_request_bdb3ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mcprequest",
            index=models.Index(
                fields=["status", "created_at"], name="mcp_request_status_69cc75_idx"
            ),
        ),
    ]
