# Generated by Django 4.2.7 on 2025-08-24 05:31

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="CollectionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("weight", models.FloatField(default=1.0)),
            ],
            options={
                "db_table": "collection_documents",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("source", models.URLField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(db_index=True, default="text", max_length=50),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("content", models.TextField()),
                ("chunk_index", models.IntegerField()),
                ("start_position", models.IntegerField(default=0)),
                ("end_position", models.IntegerField(default=0)),
                ("token_count", models.IntegerField(default=0)),
                ("embedding", pgvector.django.VectorField(dimensions=384)),
                (
                    "embedding_model",
                    models.CharField(
                        default="sentence-transformers/all-MiniLM-L6-v2", max_length=100
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "document_chunks",
            },
        ),
        migrations.CreateModel(
            name="EmbeddingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("model_path", models.CharField(max_length=255)),
                ("dimension", models.IntegerField()),
                ("max_sequence_length", models.IntegerField(default=512)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("huggingface", "Hugging Face"),
                            ("openai", "OpenAI"),
                            ("cohere", "Cohere"),
                            ("sentence_transformers", "Sentence Transformers"),
                        ],
                        default="huggingface",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "embedding_models",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("query_text", models.TextField()),
                ("query_embedding", pgvector.django.VectorField(dimensions=384)),
                ("results_count", models.IntegerField(default=0)),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("similarity", "Similarity Search"),
                            ("hybrid", "Hybrid Search"),
                            ("semantic", "Semantic Search"),
                            ("graph_rag", "Graph RAG"),
                        ],
                        default="similarity",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "search_queries",
            },
        ),
        migrations.CreateModel(
            name="VectorIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("dimension", models.IntegerField(default=384)),
                (
                    "distance_metric",
                    models.CharField(
                        choices=[
                            ("cosine", "Cosine"),
                            ("l2", "Euclidean"),
                            ("inner_product", "Inner Product"),
                        ],
                        default="cosine",
                        max_length=20,
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[("ivfflat", "IVFFlat"), ("hnsw", "HNSW")],
                        default="ivfflat",
                        max_length=20,
                    ),
                ),
                ("index_parameters", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "vector_indexes",
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("rank", models.IntegerField()),
                ("rerank_score", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "chunk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vector_store.documentchunk",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="vector_store.searchquery",
                    ),
                ),
            ],
            options={
                "db_table": "search_results",
            },
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["search_type", "created_at"],
                name="search_quer_search__510de9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["created_at"], name="search_quer_created_02141d_idx"
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="vector_store.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="collectiondocument",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vector_store.collection",
            ),
        ),
        migrations.AddField(
            model_name="collectiondocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vector_store.document"
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="documents",
            field=models.ManyToManyField(
                through="vector_store.CollectionDocument", to="vector_store.document"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["similarity_score"], name="search_resu_similar_2b3576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(fields=["rank"], name="search_resu_rank_4ce1e0_idx"),
        ),
        migrations.AddIndex(
            model_name="searchresult",
            index=models.Index(
                fields=["rerank_score"], name="search_resu_rerank__54ec6c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="searchresult",
            unique_together={("query", "chunk")},
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="document_ch_documen_15f3c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["embedding_model"], name="document_ch_embeddi_c81c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["token_count"], name="document_ch_token_c_605101_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="documents_documen_766d83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_created_3c6eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_hash"], name="documents_file_ha_3bbf78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="documents_content_7d700d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondocument",
            unique_together={("collection", "document")},
        ),
    ]
