# Generated by Django 4.2.7 on 2025-08-24 06:20

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("vector_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding_model",
            field=models.CharField(default="text-embedding-ada-002", max_length=100),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="query_embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name="vectorindex",
            name="dimension",
            field=models.IntegerField(default=1536),
        ),
    ]
