# Generated by Django 4.2.7 on 2025-08-24 05:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("density", models.FloatField(default=0.0)),
                ("modularity_score", models.FloatField(default=0.0)),
                ("summary", models.TextField(blank=True)),
                (
                    "summary_embedding",
                    pgvector.django.VectorField(blank=True, dimensions=384, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "communities",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("entity_type", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("embedding", pgvector.django.VectorField(dimensions=384)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("frequency", models.IntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "entities",
            },
        ),
        migrations.CreateModel(
            name="EntityDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("extraction_method", models.CharField(default="ner", max_length=50)),
            ],
            options={
                "db_table": "entity_documents",
            },
        ),
        migrations.CreateModel(
            name="GraphIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("entity_embedding", "Entity Embedding Index"),
                            ("community_embedding", "Community Embedding Index"),
                            ("relationship_weight", "Relationship Weight Index"),
                            ("hybrid", "Hybrid Index"),
                        ],
                        max_length=50,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("statistics", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "graph_indexes",
            },
        ),
        migrations.CreateModel(
            name="GraphQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("query_text", models.TextField()),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("graph_rag", "Graph RAG"),
                            ("entity_search", "Entity Search"),
                            ("relationship_search", "Relationship Search"),
                            ("community_search", "Community Search"),
                            ("path_search", "Path Search"),
                        ],
                        default="graph_rag",
                        max_length=50,
                    ),
                ),
                ("query_embedding", pgvector.django.VectorField(dimensions=384)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("results_count", models.IntegerField(default=0)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "graph_queries",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("schema_version", models.CharField(default="1.0", max_length=20)),
                ("statistics", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "knowledge_graphs",
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("relationship_type", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("weight", models.FloatField(default=1.0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("frequency", models.IntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "relationships",
            },
        ),
        migrations.CreateModel(
            name="RelationshipChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "extraction_method",
                    models.CharField(default="relation_extraction", max_length=50),
                ),
            ],
            options={
                "db_table": "relationship_chunks",
            },
        ),
        migrations.CreateModel(
            name="TemporalEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField()),
                ("weight", models.FloatField(default=1.0)),
                ("event_type", models.CharField(default="occurrence", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporal_edges",
                        to="graph_rag.relationship",
                    ),
                ),
            ],
            options={
                "db_table": "temporal_edges",
            },
        ),
    ]
