# Generated by Django 4.2.7 on 2025-08-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vector_store", "0001_initial"),
        ("graph_rag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipchunk",
            name="chunk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vector_store.documentchunk",
            ),
        ),
        migrations.AddField(
            model_name="relationshipchunk",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="graph_rag.relationship"
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="source_chunks",
            field=models.ManyToManyField(
                through="graph_rag.RelationshipChunk", to="vector_store.documentchunk"
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="source_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_relationships",
                to="graph_rag.entity",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="target_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_relationships",
                to="graph_rag.entity",
            ),
        ),
        migrations.AddField(
            model_name="knowledgegraph",
            name="entities",
            field=models.ManyToManyField(blank=True, to="graph_rag.entity"),
        ),
        migrations.AddField(
            model_name="graphquery",
            name="knowledge_graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="graph_rag.knowledgegraph",
            ),
        ),
        migrations.AddField(
            model_name="graphindex",
            name="knowledge_graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="indexes",
                to="graph_rag.knowledgegraph",
            ),
        ),
        migrations.AddField(
            model_name="entitydocument",
            name="chunks",
            field=models.ManyToManyField(blank=True, to="vector_store.documentchunk"),
        ),
        migrations.AddField(
            model_name="entitydocument",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vector_store.document"
            ),
        ),
        migrations.AddField(
            model_name="entitydocument",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="graph_rag.entity"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="source_documents",
            field=models.ManyToManyField(
                through="graph_rag.EntityDocument", to="vector_store.document"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="entities",
            field=models.ManyToManyField(
                related_name="communities", to="graph_rag.entity"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="knowledge_graph",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communities",
                to="graph_rag.knowledgegraph",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="parent_community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_communities",
                to="graph_rag.community",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaledge",
            index=models.Index(
                fields=["relationship", "timestamp"],
                name="temporal_ed_relatio_78b6d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="temporaledge",
            index=models.Index(
                fields=["timestamp"], name="temporal_ed_timesta_b2d72e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temporaledge",
            index=models.Index(
                fields=["event_type"], name="temporal_ed_event_t_1d2e27_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relationshipchunk",
            unique_together={("relationship", "chunk")},
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["relationship_type", "weight"],
                name="relationshi_relatio_a128ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["confidence_score"], name="relationshi_confide_8a025e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                fields=["frequency"], name="relationshi_frequen_cc66c0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("source_entity", "target_entity", "relationship_type")},
        ),
        migrations.AddIndex(
            model_name="graphquery",
            index=models.Index(
                fields=["query_type", "created_at"],
                name="graph_queri_query_t_cc2e1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="graphquery",
            index=models.Index(
                fields=["knowledge_graph", "created_at"],
                name="graph_queri_knowled_606cac_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entitydocument",
            unique_together={("entity", "document")},
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["entity_type", "confidence_score"],
                name="entities_entity__11eeea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["frequency"], name="entities_frequen_d960a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["name", "entity_type"], name="entities_name_3b9d44_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entity",
            unique_together={("name", "entity_type")},
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["knowledge_graph", "level"],
                name="communities_knowled_bd61e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["size", "density"], name="communities_size_f65743_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["modularity_score"], name="communities_modular_0b8792_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="community",
            unique_together={("knowledge_graph", "name", "level")},
        ),
    ]
