# Generated by Django 4.2.7 on 2025-08-24 06:20

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("graph_rag", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="summary_embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name="graphquery",
            name="query_embedding",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
